import type { User, Viaje } from './types';

export const users: User[] = [
  {
    id: 'user_1',
    nombre: 'Carlos Gomez',
    email: 'carlos@example.com',
    telefono: '1122334455',
    calificacion: 4.8,
    viajesComoCondcutor: 15,
    viajesComoPasajero: 5,
    fechaRegistro: new Date('2023-01-10'),
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: 'user_2',
    nombre: 'Ana Rodriguez',
    email: 'ana@example.com',
    telefono: '1166778899',
    calificacion: 4.9,
    viajesComoCondcutor: 2,
    viajesComoPasajero: 20,
    fechaRegistro: new Date('2023-03-15'),
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: 'user_3',
    nombre: 'Lucia Fernandez',
    email: 'lucia@example.com',
    telefono: '1133445566',
    calificacion: 4.5,
    viajesComoCondcutor: 0,
    viajesComoPasajero: 8,
    fechaRegistro: new Date('2023-05-20'),
    avatarUrl: 'https://placehold.co/100x100.png',
  },
];

export const trips: Viaje[] = [
  {
    id: 'viaje_1',
    conductorId: 'user_1',
    conductorNombre: 'Carlos Gomez',
    conductorTelefono: '1122334455',
    conductorAvatarUrl: 'https://placehold.co/100x100.png',
    origen: 'San Antonio de Areco',
    destino: 'Buenos Aires',
    fecha: new Date(new Date().setDate(new Date().getDate() + 1)),
    hora: '08:00',
    asientosTotales: 4,
    asientosDisponibles: 2,
    precio: 2500,
    descripcion: 'Voy por Au. Panamericana. Cómodo y seguro. Solo equipaje de mano.',
    estado: 'disponible',
    pasajeros: [
      { usuarioId: 'user_2', nombre: 'Ana Rodriguez', telefono: '1166778899', asientosReservados: 1, avatarUrl: 'https://placehold.co/100x100.png' },
      { usuarioId: 'user_3', nombre: 'Lucia Fernandez', telefono: '1133445566', asientosReservados: 1, avatarUrl: 'https://placehold.co/100x100.png' },
    ],
    fechaCreacion: new Date('2024-05-20T10:00:00Z'),
  },
  {
    id: 'viaje_2',
    conductorId: 'user_2',
    conductorNombre: 'Ana Rodriguez',
    conductorTelefono: '1166778899',
    conductorAvatarUrl: 'https://placehold.co/100x100.png',
    origen: 'Buenos Aires',
    destino: 'San Antonio de Areco',
    fecha: new Date(new Date().setDate(new Date().getDate() + 1)),
    hora: '18:30',
    asientosTotales: 3,
    asientosDisponibles: 1,
    precio: 2800,
    descripcion: 'Regreso a casa. Puedo pasar a buscar por zona Belgrano. Aire acondicionado y buena música.',
    estado: 'disponible',
    pasajeros: [
       { usuarioId: 'user_1', nombre: 'Carlos Gomez', telefono: '1122334455', asientosReservados: 2, avatarUrl: 'https://placehold.co/100x100.png' },
    ],
    fechaCreacion: new Date('2024-05-21T11:30:00Z'),
  },
  {
    id: 'viaje_3',
    conductorId: 'user_1',
    conductorNombre: 'Carlos Gomez',
    conductorTelefono: '1122334455',
    conductorAvatarUrl: 'https://placehold.co/100x100.png',
    origen: 'San Antonio de Areco',
    destino: 'Buenos Aires',
    fecha: new Date(new Date().setDate(new Date().getDate() + 2)),
    hora: '09:00',
    asientosTotales: 4,
    asientosDisponibles: 4,
    precio: 2500,
    descripcion: 'Viaje por la mañana. Salida puntual.',
    estado: 'disponible',
    pasajeros: [],
    fechaCreacion: new Date('2024-05-22T08:00:00Z'),
  },
  {
    id: 'viaje_4',
    conductorId: 'user_3',
    conductorNombre: 'Lucia Fernandez',
    conductorTelefono: '1133445566',
    conductorAvatarUrl: 'https://placehold.co/100x100.png',
    origen: 'Buenos Aires',
    destino: 'San Antonio de Areco',
    fecha: new Date(new Date().setDate(new Date().getDate() + 3)),
    hora: '17:00',
    asientosTotales: 2,
    asientosDisponibles: 0,
    precio: 3000,
    descripcion: 'Viaje en auto chico, solo 2 lugares. Pet friendly.',
    estado: 'completo',
    pasajeros: [
        { usuarioId: 'user_1', nombre: 'Carlos Gomez', telefono: '1122334455', asientosReservados: 1, avatarUrl: 'https://placehold.co/100x100.png' },
        { usuarioId: 'user_2', nombre: 'Ana Rodriguez', telefono: '1166778899', asientosReservados: 1, avatarUrl: 'https://placehold.co/100x100.png' },
    ],
    fechaCreacion: new Date('2024-05-22T15:00:00Z'),
  },
];
